export { suggestionsClient as SuggestionsClient } from './suggestions-client';
export { SuggestionsClientV2 } from './suggestions-client-v2';
export * from './types';
export {
  CreateSavedQueryParams,
  UpdateSavedQueryParams,
  SavedQuery,
  SearchCategory,
  FetchQueriesResponse,
  SearchRule,
  SearchToken,
  SearchRulesResponse,
  SuggestionNamespaceSpecification,
  SuggestValueSpecification,
  SuggestedFieldSpecification,
  SuggestedFieldDescriptor,
  SuggestionQueryGlobalOptions,
  SuggestionsRequestParams,
  SuggestSearchResponse,
  SuggestedTerm,
  SuggestedTermValue,
  SuggestionsSearchQuery,
  DescribeSearchRequest,
  DescribeSearchResponse,
  TranslateSearchRequest,
  TranslateSearchResponse,
  SearchTemplate,
  SearchTemplatesResponse,
  FetchGroupsQueryParams,
  SavedGroup,
} from './suggestions-service.types';
