version: 1.0
service_name: nepal-client-libs

stages:
    -
        name: PR Test
        when:
            - pull_request
        image: node:13
        compute_size: small
        commands:
            - npm install
            - node_modules/lerna/cli.js info
            - echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list
            - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
            - apt-get update && apt-get -y install google-chrome-stable
            - export CHROME_BIN='/usr/bin/google-chrome'
#            - npm run test
#            - npm run lint
            - npm run build
            - npx madge --circular --extensions ts --ts-config tsconfig.json packages

    -
        name: Master Push - Publish
        when:
            - push: ['master']
        image: node:13
        compute_size: small
        commands:
            - echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list
            - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
            - apt-get update && apt-get -y install google-chrome-stable
            - export CHROME_BIN='/usr/bin/google-chrome'
            - |
                set -ex

                printenv

                if [ -z "$NPM_TOKEN" ]
                then
                    echo "\$NPM_TOKEN is empty"
                    exit 1
                fi

                echo //registry.npmjs.org/:_authToken="$NPM_TOKEN" > .npmrc
                npm whoami


                # Release section
                curl -fsSL https://github.com/github/hub/raw/master/script/get | bash -s 2.14.2
                GITHUB_TOKEN=$ALPS_GH_TOKEN


                npm install
                node_modules/lerna/cli.js info

                node_modules/lerna/cli.js publish from-package --dist-tag core-beta

            - echo done
