/**
 * ScanScheduler Service
 * Advanced Scan Scheduling API
 *
 * OpenAPI spec version: 2.0
 * Contact: support@alertlogic.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ScanWindow } from './scanWindow';

/**
 * Scan window for continuous period between two days of month, with start time/day and end time/day.
 */
export interface ScanWindowContinuousPeriodMonthly extends ScanWindow {
    type: ScanWindowContinuousPeriodMonthly.TypeEnum;
    /**
     * Day of month when continuous scanning window commences (`1 - 31`).
     * If selected day is not applicable to the month, the nearest date will be used instead.
     * E.g. a scan set to run on the \"30th\" will run February 28th. For API consumer's convenience `31`
     * will ALWAYS be considered as the  END_OF_MONTH wildcard.
     */
    startDay: number;
    /**
     * Time of day when continuous scanning window commences (24h format)
     */
    startTime: string;
    /**
     * Day of month when continuous scanning window ends (`1 - 31`)
     * If selected day is not applicable to the month, the nearest date will be used instead.
     * E.g. a scan set to run on the \"30th\" will run February 28th. For API consumer's convenience `31`
     * will ALWAYS be considered as the  END_OF_MONTH wildcard.
     */
    endDay: number;
    /**
     * Time of day when continuous scanning window ends (24h)
     */
    endTime: string;
}
export namespace ScanWindowContinuousPeriodMonthly {
    export type TypeEnum = 'monthly_period';
    export const typeEnum = {
        Period: 'monthly_period' as TypeEnum
    };
}
