/**
 * ScanScheduler Service
 * Advanced Scan Scheduling API
 *
 * OpenAPI spec version: 2.0
 * Contact: support@alertlogic.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ScanScopeItem } from './scanScopeItem';

export interface ScanScopeItemTag extends ScanScopeItem { 
    key?: string;
    value?: string;
    type?: string;
}