/**
 * ScanScheduler Service
 * Advanced Scan Scheduling API
 *
 * OpenAPI spec version: 2.0
 * Contact: support@alertlogic.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ScanScopeItemAsset } from './scanScopeItemAsset';
import { ScanScopeItemCIDR } from './scanScopeItemCIDR';
import { ScanScopeItemTag } from './scanScopeItemTag';

export interface ScanScope {
    includeFutureAssets?: boolean;
    include?: Array<ScanScopeItemAsset | ScanScopeItemCIDR | ScanScopeItemTag>;
    exclude?: Array<ScanScopeItemAsset | ScanScopeItemCIDR | ScanScopeItemTag>;
}
