/**
 * ScanScheduler Service
 * Advanced Scan Scheduling API
 *
 * OpenAPI spec version: 2.0
 * Contact: support@alertlogic.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ScanScope } from './scanScope';
import { ScanWindowContinuousPeriodMonthly } from './scanWindowContinuousPeriodMonthly';
import { ScanWindowContinuousPeriodWeekly } from './scanWindowContinuousPeriodWeekly';
import { ScanWindowSelectedDaysOfMonth } from './scanWindowSelectedDaysOfMonth';
import { ScanWindowSelectedDaysOfWeek } from './scanWindowSelectedDaysOfWeek';

/**
 * Scan Schedule definition.
 */
export interface Schedule {
    readonly id?: string;
    name?: string;
    enabled?: boolean;
    typeOfScan?: Schedule.TypeOfScanEnum;
    scanFrequency?: Schedule.ScanFrequencyEnum;
    scanWindows?: Array<ScanWindowSelectedDaysOfWeek | ScanWindowSelectedDaysOfMonth | ScanWindowContinuousPeriodWeekly | ScanWindowContinuousPeriodMonthly>;
    scanScope?: ScanScope;
}
export namespace Schedule {
    export type TypeOfScanEnum = 'vulnerability' | 'external' | 'discovery';
    export const typeOfScanEnum = {
        Vulnerability: 'vulnerability' as TypeOfScanEnum,
        External: 'external' as TypeOfScanEnum,
        Discovery: 'discovery' as TypeOfScanEnum
    };
    export type ScanFrequencyEnum = 'automatic' | 'daily' | 'weekly' | 'monthly';
    export const scanFrequencyEnum = {
        Automatic: 'automatic' as ScanFrequencyEnum,
        Daily: 'daily' as ScanFrequencyEnum,
        Weekly: 'weekly' as ScanFrequencyEnum,
        Monthly: 'monthly' as ScanFrequencyEnum
    };
}
