export const EPMSGS_PROPERTIES_DICTIONARY = {
    "uad_dea": "Destination Encryption Type",
    "uad_sdt": "Source Drive Type",
    "uad_sbt": "Source Bus Type",
    "uad_dcf": "Attachment Was Destination File Captured",
    "uad_medid": "Machine event detail ID for the device",
    "uad_dp": "Destination path",
    "uad_sp": "Source path",
    "uad_dir": "Destination is Removable Drive",
    "dg_file_size": "File size",
    "uad_sea": "Source Encryption Type",
    "uad_br": "Bytes read",
    "uad_sc": "Source capture status",
    "uad_bw": "Bytes written",
    "uad_scf": "Attachment source has capture",
    "uad_dvn": "Destination volume serial number",
    "uad_sir": "Source is Removable Drive",
    "uad_opf": "Operation failed",
    "uad_ot": "Detail type",
    "uad_dfi": "Destination file ID",
    "uad_ddh": "Destination Device GUID",
    "uad_svn": "Source volume serial number",
    "uad_sfc": "Source was classified",
    "uad_ops": "Operation status",
    "uad_ddt": "Destination Drive Type",
    "uad_sdh": "Source device GUID",
    "uad_dbt": "Device Bus Type",
    "uad_sfi": "Source file ID",
    "dg_guid": "Globally unique ID",
    "ua_ot": "Network or App Compliance Operation",
    "dg_time": "Time event occurred",
    "ua_ar": "Removable device used",
    "ua_rc": "Repeat Count",
    "ua_meid": "Computer Event UID",
    "ua_eel": "Local end time",
    "ua_la": "Is User Local Admin",
    "ua_md": "Laptop with agent",
    "ua_md5": "DG Generated MD5 hash",
    "ua_eeu": "Event end time",
    "dg_user": "User",
    "dg_local_timestamp": "Event Local Time",
    "dg_md5": "MD5 Hash",
    "ua_dn": "User domain",
    "dg_hc": "Has Classification",
    "pi_sesid": "User session ID",
    "dg_fin": "File Internal Name",
    "pi_cmdln": "Application Command Line",
    "pi_dspn": "Signature executable",
    "pi_ppf": "Parent process flags",
    "pi_pf": "Process flags",
    "pi_ph": "Process hash",
    "pi_fml": "Process local modify time",
    "pi_pph": "Parent Process ID",
    "dg_sha1": "Process SHA1",
    "dg_sha256": "Process SHA256",
    "pi_ps": "Process State",
    "pi_fmu": "Process UTC Modify Time",
    "dg_cn": "Application Company Name",
    "pi_ema": "Email address",
    "pi_dssb": "Signature Subject",
    "pi_fp": "Process path",
    "pi_in": "Process image name",
    "pi_fs": "Process File Size",
    "pi_psl": "Process local start time",
    "pi_sid": "User SID",
    "pi_fd": "File Description",
    "pi_psu": "Process UTC start time",
    "pi_vs": "Is virtual session",
    "pi_fau": "Process UTC Access Time",
    "pi_pmd5": "Parent MD5 hash",
    "pi_un": "User name",
    "pi_dn": "Process domain",
    "pi_fal": "Process Local Access Time",
    "pi_pfp": "Parent process path",
    "pi_fcu": "Process UTC Creation Time",
    "pi_fcl": "Process local creation time",
    "dg_fon": "Application Original Name",
    "pi_pin": "Parent process internal name",
    "dg_lc": "DLL legal copyright info",
    "dg_dsi": "Signature Issuer",
    "dg_gid": "PKI Group ID",
    "pi_dss": "Signature Subject",
    "dg_pid": "Process PID",
    "dg_fv": "File version",
    "dg_parent_name": "Parent Application",
    "dg_sesid": "Session ID",
    "pi_pki": "PKI authenticated",
    "dg_agent_md5": "DG generated MD5 hash",
    "pi_t": "X86 or x64",
    "pi_v": "Bundle version",
    "dev_friendlyname": "Friendly name",
    "dev_sernum": "Serial number",
    "dev_vendorid": "Manufacturer ID",
    "dev_rempolicy": "Storage removal policy",
    "dev_customid": "Custom ID",
    "dev_devclass": "Device class",
    "dev_dt": "Drive type",
    "dev_bt": "Storage bus type",
    "dev_vendor": "Vendor name",
    "dev_prdname": "Product name",
    "dev_suppredfail": "Supports predict failure",
    "dg_bid": "Bundle ID",
    "dg_bundle_location": "Bundle location",
    "dg_mid": "Machine ID",
    "dg_first": "Is First of Many detail events",
    "dg_display": "Display name",
    "dg_processed_time": "Server processed time",
    "dg_tenant_name": "Tenant Name",
    "dg_tenant_id": "Tenant ID",
    "dg_proc_file_ext": "Process file extension",
    "dg_proc_dir": "Process directory",
    "dg_proc_file_name": "Process file name",
    "dg_src_file_ext": "Source file extension",
    "dg_src_dir": "Source directory",
    "dg_src_file_name": "Source file name",
    "dg_src_scheme": "Source Scheme",
    "dg_dst_file_ext": "Destination file extension",
    "dg_dst_dir": "Destination directory",
    "dg_dst_file_name": "Destination file name",
    "dg_dst_scheme": "Destination Scheme",
    "dg_machine_name": "Machine name",
    "dg_machine_type": "Machine type",
    "dg_mac_address": "MAC address",
    "dg_os_name": "OS Name",
    "dg_agent_version": "Agent Version",
    "dg_domain_name": "Computer user domain name",
    "pi_nda": "Network appliance generated",
    "dg_local_hour": "Local Hour of Day",
    "dg_local_dow": "Local Day of Week",
    "dg_local_month": "Local Month",
    "dg_local_woy": "Local Week of Year",
    "dg_vt_status": "Threat Intel Status",
    "dg_vt_sub_time": "Threat Intel Submitted Time",
    "dg_vt_count": "Threat Intel Scanner Count",
    "dg_vt_pos_count": "Threat Intel Scanner Matches",
    "dg_vt_time": "Threat Intel Scan Time",
    "dg_vt_pos_names": "Threat Intel Match Names",
    "dg_user_id": "User ID",
    "dg_user_surname": "User Last Name",
    "dg_user_given_name": "User First Name",
    "dg_user_email": "User email",
    "dg_user_manager": "User manager",
    "dg_user_manager_email": "User manager email",
    "dg_user_department": "User department",
    "dg_user_company": "User company",
    "dg_user_business_category": "User business category",
    "dg_user_division": "User division",
    "dg_user_telephone": "User telephone number",
    "dg_user_business_title": "User business title",
    "dg_user_physical_delivery_office": "User office name",
    "dg_user_city_name": "User city name",
    "dg_user_country_name": "User country name",
    "dg_user_zip": "User zip code",
    "dg_flags": "Event Flags",
    "dg_was_mobile_copy": "File copied to mobile device",
    "dg_atp_classified": "ATP classification rule",
    "dg_wrv": "Was Rule Violation",
    "dg_wdb": "Was Rule Violation Blocked",
    "dg_integration_type": "Integration type",
    "ua_ob": "Network Direction",
    "ua_ra": "Remote IP address",
    "ua_sa": "Source IP address",
    "ua_lp": "Source port",
    "ua_rp": "Remote port",
    "ua_hn": "DNS host",
    "dg_pv": "Product version",
    "ua_pt": "Protocol",
    "ua_pm": "EventTypes medium",
    "ua_pa": "Is Private Address",
    "ua_ad": "Adapter name",
    "ua_wif": "Wireless infrastructure mode",
    "ua_wi": "Is wireless connection",
    "ua_we": "Encryption status",
    "ua_ssid": "Wireless SSID",
    "ua_up": "URL",
    "ua_wam": "Wireless Auth mode",
    "ua_wap": "Access point",
    "pi_dsct": "Application Sign Time",
    "dg_pn": "Product name",
    "pi_dsi": "Signature Issuer",
    "dg_url_port": "URL port",
    "dg_url_scheme": "URL Scheme",
    "dg_url_context_path": "URL context path",
    "dg_url_host": "URL Host",
    "dg_alert.dg_name": "Detection Name",
    "dg_alarm_sev": "Alarm Severity",
    "dg_alarm_name": "Alarm Name",
    "dg_det_id": "Detection rule ID",
    "dg_det_type": "Detection rule type",
    "pi_pel": "Process local end time",
    "pi_peu": "Process UTC end time"
};

export const EPMSGS_BLACKLIST_PROPERTIES = [
    "__contentType",
    "__description",
    "__irisType",
    "__normalizedTime",
    "__relatedOrAssociated",
    "__source",
    "dg_alarm_assignee",
    "dg_alarm_assignee_id",
    "dg_alarm_modified",
    "dg_alarm_modified_by",
    "dg_vt_count",
    "dg_vt_pos_count",
    "dg_vt_status",
    "dg_vt_sub_time",
    "dg_vt_time"
];

export class EPMSGSUtils {
    static renameProperties (obj: object | any[], propertiesMap: {[key: string]: string}): object {
        if (typeof obj !== 'object' || obj === null) {
            return obj;
        }

        if (Array.isArray(obj)) {
            return obj.map(item => EPMSGSUtils.renameProperties(item, propertiesMap));
        }

        const renamedObj = {};

        for (const key in obj) {
            if (obj.hasOwnProperty(key)) {
                if(propertiesMap[key]) {
                    console.log("changed key", key);
                }
                const newName = propertiesMap[key] || key;
                renamedObj[newName] = EPMSGSUtils.renameProperties(obj[key], propertiesMap);
            }
        }
        return renamedObj;
    }

    static removeProperties(obj, propsToRemove: string[]) {
        let newObj = { ...obj };
        propsToRemove.forEach(prop => {
            delete newObj[prop];
        });
        return newObj;
    }
}
